language: node_js
node_js: node
before_install: 
install:
  - npm install
script: 
  - npm run test-with-coverage
deploy:
  provider: heroku
  api_key:
    secure: VHWqe5O6Bz4hWpXMYvW+xoRYn+4qeOR6MJKq4eeRnrbKeqNn4Atyb5BW3G+dnR/LwALgxMKCxqJ4AdNTmYGpuyLQ/mAY/OF0uvJKbZxlFBYdkjajRFke7s4GS6wCr/uhOPX87BduomUUuf8SJbYugRMMxQrGUhF7iev32Y8Yqy2ikzi2x/16pYZtErYQSxWV8uCC2rP6HduQorahaAE2wH8KrgLxoQZQIpjQmAlR7NBjBLnp7IPWVAa36r9qHbmDiYxBSYlrXBAtVGoGwMS81wFur4SQUXyOzjIwzMl3TaJt+hyx87eNpxUx6DMHf8z7rVDq3leJxN2JzFRuLisMixfu+DvFjaReGhp0tZDMaGFknsG+L8mNG4hsUep9UufOLC7ngZ42cVSAnbdUJ41R7h6J7tWobh7qrkHVXunCusOAVml//0ZCyqYSM2hW4J7pnnRKiNY03PQ2XF7IVpOeIGtsO2yGqfbfhB6P409fVOwTbBKzguCSRxBMcMfGHtBpCweVmytUOFf3YOmhwG1jBFeo7tv5nPgJVMN2C+N9hPqu2N5169UilsVwA0FUDKesYK2azjfvGahShEBZ1da7poqLUNvHHVYZFlZDLxM1DX/yPe0hh9ZeeNE7U0Xu8oSEIhv+VR3yLCQZTXHEJ/iqBu9EKVTXsg+k2hlqa3Upy3o=
  app: abastify-be
  on:
    branch: master
